version: "3.9"
services:
  db:
    build:
      context: ./shopping-list-db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: db_shopping-list
    networks:
      - default
    volumes:
      - shopping-list_db:/var/lib/mysql
      
  backend:
    build:
      context: ./shopping-list-backend
      dockerfile: Dockerfile
    environment:
      JWT_KEY: "jda89dj98023u0 0u0 ))@)(#*)#*)@#*)(* )) u89dsijzhco 013- sdfdfmsdfsd,f,sf, ) @#)*)#*)#)(*#)(#)(#)(#)(# @!!!!!"
      DB_TYPE: mysql
      DB_HOST: db
      DB_USERNAME: root
      DB_DATABASE: db_shopping-list
      DB_PASSWORD: password
      FE_DOMAIN: localhost
      FE_SSL: false
      FE_CORS_ORIGIN: http://localhost:3000
    ports:
      - "3002:3002"
    volumes:
      - ./shopping-list-backend:/app 
      - shopping-list_be:/app/node_modules
    depends_on:
      - db
    networks:
      - default
      
  frontend:
    build:
      context: ./shopping-list-frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: http://localhost:3002/api
      WATCHPACK_POLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./shopping-list-frontend:/app 
      - shopping-list_fe:/app/node_modules
    depends_on:
      - backend
volumes:
  shopping-list_fe:
  shopping-list_be:
  shopping-list_db:
    driver: local
networks:
  default:
  