version: "3.9"
services:
  db:
    build:
      context: ./shopping-list-db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: db_shopping-list
    networks:
      - default
      
  backend:
    build:
      context: ./shopping-list-backend
      dockerfile: Dockerfile
    environment:
      JWT_KEY: "jda89dj98023u0 0u0 ))@)(#*)#*)@#*)(* )) u89dsijzhco 013- sdfdfmsdfsd,f,sf, ) @#)*)#*)#)(*#)(#)(#)(#)(# @!!!!!"
      DB_TYPE: mysql
      DB_HOST: db
      DB_USERNAME: root
      DB_DATABASE: db_shopping-list
      DB_PASSWORD: password
    ports:
      - "3000:3000"
    volumes:
      - ./shopping-list-backend:/app 
      - /app/node_modules
    depends_on:
      - db
    networks:
      - default
      
networks:
  default:
